Template docstrings update
ContinualAI/avalanche pull request #1297
Opened 2023-02-08 22:03 UTC by HamedHemati

2023-02-10 21:17 UTC, HamedHemati commented
Latest update:

- Added necessary attributes for model adaptation after each sub-exp.
- Re-added model adaptation for task-free streams.

2023-02-11 15:29 UTC, AntonioCarta requested changes

2023-02-11 15:29 UTC, AntonioCarta commented on avalanche/benchmarks/scenarios/online_scenario.py
> +            parameter must be set to True.
remove this comment

2023-02-12 21:07 UTC, HamedHemati commented on avalanche/benchmarks/scenarios/online_scenario.py
> +            parameter must be set to True.
Done

2023-02-13 13:47 UTC, merged