L2p
ContinualAI/avalanche pull request #1302
Opened 2023-02-20 08:47 UTC by JuliousHurtado

Implementation of L2P methods
"Wang, Zifeng, et al. "Learning to prompt for continual learning."  Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2022."
The contribution consists in:
- Adding a file with the transformers architecture to the models (based on timm library)
- Adding a file with the prompts classes
- Supervised Strategy that implement the training pipeline and loss proposed by the authors
- Add test for L2P strategy, base on a simple MLP
- Remove extra  `_train_exp` in base_sgd

2023-02-23 08:30 UTC, AntonioCarta requested changes

2023-02-23 08:30 UTC, AntonioCarta commented on avalanche/models/prompt.py
> +class Prompt(nn.Module):
can you add docstrings here?

2023-02-23 08:30 UTC, AntonioCarta commented on avalanche/models/prompt.py
> +        prompt_key_init="uniform",
doc with all arguments

2023-02-23 08:30 UTC, AntonioCarta commented on avalanche/models/prompt.py
> +    def forward(self, x_embed, prompt_mask=None, cls_features=None):
doc with all arguments

2023-02-23 08:30 UTC, AntonioCarta commented on avalanche/models/timm_vit.py
> +default_cfgs = {
do we need these configs in avalanche? aren't they already available on timm? I would avoid copy-pasting things that people can take from somewhere else.

2023-02-23 08:30 UTC, AntonioCarta commented on avalanche/training/supervised/l2p.py
> +    Learning to Prompt (L2P) plugin.
it's not a plugin, it's a strategy (I know that avalanche is a bit confusing on these differences).

2023-02-23 08:32 UTC, AntonioCarta commented
Hey @JuliousHurtado it's still not completely clear to me the relationship between Avalanche and timm. Ideally, we should use timm for vision transformers. I don't understand why you added `vit.py` and `timm_vit.py`.
If we reuse timm we don't have to maintain vision transformers ourselves, which is much better for us. Of course it's fine to add them if we need anything that is CL-specific.

2023-03-13 09:13 UTC, JuliousHurtado commented
Hey @AntonioCarta, I just finished reviewing your comments. I focus on distinguishing what remains in timm from what belongs to CL. Now, the vit.py models are imported from timm_vit.py, which is the VisualTransformer from timm, but we the modification needed to work in CL with Prompts.
Let me know what you think.

2023-03-13 10:29 UTC, merged